Таблица Readers:

In [ ]:
from faker import Faker

import random

fake = Faker()

for i in range(1000):
    name = fake.name()
    address = fake.address().replace('\n', '\\n')
    phone_number = ''.join([str(random.randint(0, 9)) for _ in range(10)])
    email = fake.email()
    birthdate = fake.date_of_birth().strftime('%Y-%m-%d')
    reader_id = i + 1

    print("INSERT INTO Readers (НомерЧитБилета, ФИО, Адрес, Телефон, ЭлПочта, ДатаРождения) VALUES (%s, '%s', '%s', '%s', '%s', '%s')" % (reader_id, name, address, phone_number, email, birthdate))

Таблица Authors:

In [ ]:
from faker import Faker

fake = Faker()

for i in range(1000):
    author_name = fake.name()
    author_years = fake.year()
    author_id = i + 1

    print("INSERT INTO Authors (AuthorID, ФИО, ГодыЖизни) VALUES (%s, '%s', '%s')" % (author_id, author_name, author_years))

Таблицв PUbHouse:

In [ ]:
from faker import Faker

fake = Faker()

for i in range(1000):
    pub_name = fake.company()
    pub_address = fake.address().replace('\n', '\\n')
    pub_phone = ''.join([str(random.randint(0, 9)) for _ in range(10)])
    pub_id = i + 1

    print("INSERT INTO PUbHouse (ИздательствоID, Название, Адрес, Телефон) VALUES (%s, '%s', '%s', '%s')" % (pub_id, pub_name, pub_address, pub_phone))

Тапблица Theme:

In [ ]:
from faker import Faker

fake = Faker()

for i in range(1000):
    theme_name = fake.word()
    theme_desc = fake.sentence()
    theme_id = i + 1

    print("INSERT INTO Theme (ТематикаID, Название, Описание) VALUES (%s, '%s', '%s')" % (theme_id, theme_name, theme_desc))

Таблица Workers:

In [17]:
from faker import Faker

fake = Faker()

for i in range(1000):
    worker_name = fake.name()
    worker_position = fake.job()
    worker_email = fake.email()
    worker_id = i + 1

    print("INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (%s, '%s', '%s', '%s')" % (worker_id, worker_name, worker_position, worker_email))

INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (1, 'Jeffrey Lee', 'Horticultural consultant', 'kwilson@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (2, 'Kim Elliott', 'Cartographer', 'baileylacey@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (3, 'Marc Fernandez', 'Surgeon', 'wilsonmark@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (4, 'Matthew Hart', 'Ecologist', 'thomasbryan@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (5, 'Morgan Thomas', 'Actor', 'qphillips@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (6, 'Alexander Malone', 'Aid worker', 'jamesarmstrong@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (7, 'Christine Cortez', 'Health promotion specialist', 'nreyes@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (8, 'Kelly Waller', 'Armed forces logistics/support/administrative officer', 'marshmichael@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (9, 'Daniel Crosby', 'Automotive engineer', 'vjohnson@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (10, 'Jessica Ryan', 'Legal executive', 'walkernathaniel@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (11, 'Michael Stone', 'Surgeon', 'beckyrobertson@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (12, 'Tyler Lawrence', 'Hotel manager', 'jordanhunt@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (13, 'John Miller', 'Estate agent', 'robertsjoseph@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (14, 'Tristan Williams', 'Librarian, academic', 'ajackson@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (15, 'Eric Compton', 'Medical technical officer', 'jamesgood@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (16, 'Kelly Boyd', 'Chemical engineer', 'thomas77@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (17, 'Bobby Knight', 'Doctor, hospital', 'julie95@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (18, 'Jessica Holland', 'Museum education officer', 'robertsdavid@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (19, 'Kathryn Avila', 'Prison officer', 'xhicks@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (20, 'Lauren Shaw', 'Local government officer', 'gonzalezcindy@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (21, 'Mark Green', 'Consulting civil engineer', 'nsimpson@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (22, 'Martin Berry', 'Best boy', 'leecheryl@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (23, 'Brittney Perkins', 'Engineer, structural', 'paulwood@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (24, 'Gerald Kelly', 'Scientist, clinical (histocompatibility and immunogenetics)', 'cynthiaschneider@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (25, 'Frances Bowers', 'Orthoptist', 'nicole13@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (26, 'Cindy Carpenter', 'Teacher, English as a foreign language', 'vgonzalez@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (27, 'Jennifer Smith', 'IT sales professional', 'tlucero@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (28, 'Vicki Daniels', 'Engineer, control and instrumentation', 'crawfordbryan@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (29, 'Andrew Harmon', 'Industrial buyer', 'nchapman@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (30, 'Breanna Campbell', 'Lexicographer', 'tli@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (31, 'Angela Keller', 'Journalist, magazine', 'qcummings@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (32, 'David Perez', 'Maintenance engineer', 'brandoncross@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (33, 'Joseph Watkins', 'Applications developer', 'housemary@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (34, 'Roy Cummings', 'Sport and exercise psychologist', 'brian80@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (35, 'Richard Palmer', 'Interpreter', 'leah01@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (36, 'John Vargas', 'Civil Service administrator', 'tony49@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (37, 'Christopher Downs', 'Local government officer', 'jason82@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (38, 'Christopher Bird', 'Insurance broker', 'eileenhart@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (39, 'Michael Griffin Jr.', 'Senior tax professional/tax inspector', 'christopher47@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (40, 'Sara Lamb', 'Advertising account executive', 'douglasfrederick@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (41, 'James Ali', 'Corporate treasurer', 'kjacobs@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (42, 'Deanna Sosa MD', 'Mental health nurse', 'samanthawang@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (43, 'Mark Davis', 'Administrator, education', 'nancy41@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (44, 'Jerome Hurst', 'Merchandiser, retail', 'christopherruiz@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (45, 'Cynthia Kerr', 'Chemist, analytical', 'krista02@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (46, 'Paul Ramirez', 'Psychiatric nurse', 'uramirez@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (47, 'Angelica Harris', 'Maintenance engineer', 'ryankim@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (48, 'Wanda Koch', 'Communications engineer', 'matthewking@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (49, 'Kelly Padilla', 'Town planner', 'millerraymond@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (50, 'Rhonda White', 'Trading standards officer', 'taylorjohn@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (51, 'Willie Small', 'Corporate treasurer', 'wigginsedwin@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (52, 'Jamie Strong', 'Publishing rights manager', 'jodycarroll@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (53, 'Sarah Stevens', 'Photographer', 'anthonymiller@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (54, 'Robin Burton', 'Travel agency manager', 'michelle06@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (55, 'Rebecca Townsend', 'Advertising copywriter', 'marissa66@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (56, 'Derek Rose', 'Therapist, horticultural', 'carl59@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (57, 'Kristi Hernandez', 'Automotive engineer', 'berrybrian@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (58, 'Kenneth Pham', 'Investment analyst', 'dgordon@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (59, 'John Snyder', 'Financial adviser', 'megan94@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (60, 'Shannon Ibarra', 'Psychologist, forensic', 'johnsoncarmen@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (61, 'Leslie Mcdonald', 'Dentist', 'merrittdeborah@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (62, 'Jose Mitchell', 'Operations geologist', 'pamela45@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (63, 'Anne Johnston', 'Immigration officer', 'rluna@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (64, 'Kristen Barrera', 'Maintenance engineer', 'ian26@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (65, 'Cynthia Nelson', 'Horticultural consultant', 'fisherjennifer@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (66, 'Stacy Conner', 'Contracting civil engineer', 'kristen54@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (67, 'Emily Steele', 'Waste management officer', 'cindyyu@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (68, 'Elizabeth Simmons', 'Chief Financial Officer', 'tonyaherrera@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (69, 'Diana Howe', 'Psychologist, forensic', 'ryandavis@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (70, 'Roger Suarez', 'Police officer', 'stewartamanda@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (71, 'Katherine Goodman', 'Petroleum engineer', 'qclark@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (72, 'Rebecca Garza', 'Data scientist', 'scottbell@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (73, 'Laura Gibbs', 'Engineer, technical sales', 'lwalton@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (74, 'Regina Sanchez', 'Civil Service administrator', 'matthewbailey@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (75, 'Edward Kaiser', 'Passenger transport manager', 'christine42@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (76, 'Steven Anthony', 'Medical laboratory scientific officer', 'mejiadawn@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (77, 'Mark Hendrix', 'Data scientist', 'taylor87@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (78, 'Tracy Gibbs', 'Landscape architect', 'peteraguilar@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (79, 'Erica Larson', 'Land', 'nathanmurray@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (80, 'Shawn Mendoza', 'Quarry manager', 'znunez@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (81, 'Angela Reid', 'Magazine journalist', 'bwarren@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (82, 'Robert Morales', 'Maintenance engineer', 'kinggary@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (83, 'Donald Villanueva', 'Freight forwarder', 'suttonphilip@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (84, 'Richard Andrews', 'Geographical information systems officer', 'hroberts@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (85, 'John Williams', 'Commercial horticulturist', 'pgraham@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (86, 'Joshua Romero', 'Optician, dispensing', 'jason16@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (87, 'Nancy Morales', 'IT sales professional', 'qmckay@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (88, 'Richard Huang', 'Ranger/warden', 'edward92@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (89, 'Cody Norris', 'Lecturer, further education', 'westkenneth@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (90, 'Destiny Diaz', 'Orthoptist', 'barbaradawson@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (91, 'George Mcclure', 'Sport and exercise psychologist', 'codyfrazier@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (92, 'Melissa Craig', 'Trade union research officer', 'pchavez@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (93, 'Elizabeth Smith', 'Horticultural consultant', 'wpatterson@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (94, 'Mark Williams', 'Community development worker', 'riverakathleen@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (95, 'James Leonard', 'Facilities manager', 'hayesandrew@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (96, 'Molly Moore', 'Publishing copy', 'greerdaniel@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (97, 'Brian Mclaughlin', 'Hotel manager', 'frances56@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (98, 'Randy Ross', 'Soil scientist', 'brianluna@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (99, 'Benjamin Fernandez', 'Engineer, aeronautical', 'costapaula@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (100, 'Jason Gardner', 'Hydrographic surveyor', 'karen49@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (101, 'Michael Hall', 'Call centre manager', 'hopkinsmary@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (102, 'Natalie Simmons', 'Exhibitions officer, museum/gallery', 'ajohnson@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (103, 'Justin Davis', 'Solicitor, Scotland', 'alexisnguyen@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (104, 'Elizabeth Jones', 'Physicist, medical', 'vmorales@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (105, 'Melanie Watson', 'Furniture conservator/restorer', 'riveramark@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (106, 'Kyle Webb', 'Engineer, electronics', 'annakane@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (107, 'Roberta Henderson', 'Company secretary', 'gonzalezkimberly@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (108, 'Jacob Mcmillan', 'Chartered public finance accountant', 'susan10@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (109, 'Lorraine Swanson', 'Pensions consultant', 'rosarioraven@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (110, 'Keith Heath', 'Ecologist', 'yunicholas@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (111, 'Jimmy Howard', 'Corporate treasurer', 'frederickpatricia@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (112, 'Erin Maxwell', 'Engineer, biomedical', 'amberramos@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (113, 'George Mejia', 'Fitness centre manager', 'vmorrison@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (114, 'Angel Myers', 'Tax inspector', 'andrearodriguez@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (115, 'Mark Smith', 'Research officer, political party', 'cdelgado@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (116, 'Susan Chung', 'Theatre stage manager', 'william07@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (117, 'Craig Montgomery', 'Artist', 'whitecandice@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (118, 'Carolyn Wright', 'Chartered public finance accountant', 'tbass@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (119, 'Rebecca Harrington', 'Television/film/video producer', 'jcruz@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (120, 'Maria Webb', 'Soil scientist', 'lucasweiss@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (121, 'Amy Morrison', 'Chief of Staff', 'melaniewillis@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (122, 'Linda Hoover', 'Chartered certified accountant', 'kflores@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (123, 'Christina Nunez', 'International aid/development worker', 'xjackson@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (124, 'Ashley Sweeney', 'Product designer', 'ambersawyer@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (125, 'Michelle Silva', 'Pension scheme manager', 'laura15@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (126, 'Kimberly Washington', 'Microbiologist', 'garrett49@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (127, 'Douglas Brandt', 'Engineer, electronics', 'hoffmankayla@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (128, 'Lisa Smith', 'Hospital doctor', 'joshua61@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (129, 'Elizabeth Lowe', 'Geographical information systems officer', 'carmenwaller@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (130, 'Richard Marsh', 'Historic buildings inspector/conservation officer', 'marywalter@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (131, 'Stephanie Ward', 'Psychologist, clinical', 'kristascott@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (132, 'Debra Kelly', 'Accountant, chartered public finance', 'ecampbell@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (133, 'Andrew Oneill', 'Astronomer', 'harveynorman@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (134, 'Brenda Bell', 'Tree surgeon', 'karenterry@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (135, 'Scott Williams', 'Petroleum engineer', 'joseph66@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (136, 'Michael Ortega', 'Retail manager', 'michael62@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (137, 'James Cantu', 'Multimedia specialist', 'fortega@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (138, 'Justin Rasmussen MD', 'Water engineer', 'melissaferguson@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (139, 'John Gutierrez', 'Marine scientist', 'glenda09@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (140, 'Daniel Cabrera', 'Biomedical engineer', 'obrienerin@example.com')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (141, 'Brett Smith', 'Video editor', 'briannashelton@example.org')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (142, 'Jenna Avila', 'Electrical engineer', 'blackwelltina@example.net')
INSERT INTO Workers (СотрудникID, ФИО, Должность, ЭлПочта) VALUES (143, 'Daniel Bowers', 'Engineer, technical sales', 'allenelizabeth@example.org')

Таблица Rent:

In [ ]:
from faker import Faker
import random
from datetime import datetime, timedelta

fake = Faker()

for i in range(1000):
    book_id = random.randint(1, 1000)
    reader_id = random.randint(1, 1000)
    rent_date = fake.date_between(start_date='-1y', end_date='today').strftime('%Y-%m-%d')
    rent_cost = random.randint(100, 1000)
    return_date = (datetime.strptime(rent_date, '%Y-%m-%d') + timedelta(days=random.randint(30, 60))).strftime('%Y-%m-%d')
    rent_id = i + 1

    print("INSERT INTO Rent (АрендаID, КнигаID, ЧитательID, ДатаАренды, СтоимостьАренды, ДатаВозврата) VALUES (%s, %s, %s, '%s', %s, '%s')" % (rent_id, book_id, reader_id, rent_date, rent_cost, return_date))

Таблица Books:

In [ ]:
from faker import Faker
import random

fake = Faker()

for i in range(1000):
    book_title = fake.sentence(nb_words=3)
    book_pages = random.randint(100, 1000)
    book_isbn = ''.join([str(random.randint(0, 9)) for _ in range(13)])
    book_theme = random.randint(1, 20)
    book_id = i + 1

    print("INSERT INTO Books (BookID, Название, Страницы, ISBN, ТематикаID) VALUES (%s, '%s', %s, '%s', %s)" % (book_id, book_title, book_pages, book_isbn, book_theme))

Таблица Reservation:

In [ ]:
from faker import Faker

fake = Faker()

for i in range(1000):
    book_id = random.randint(1, 1000)
    reader_id = random.randint(1, 1000)
    reserve_date = fake.date_between(start_date='today', end_date='+1y').strftime('%Y-%m-%d')
    reserve_cost = random.randint(50, 500)
    reserve_id = i + 1

    print("INSERT INTO Reservation (РезервID, КнигаID, ЧитательID, ДатаРезерва, СтоимостьРезерва, НомерЧитБилета) VALUES (%s, %s, %s, '%s', %s, %s)" % (reserve_id, book_id, reader_id, reserve_date, reserve_cost, reader_id))

Таблица Written:

In [ ]:
import random

for i in range(1000):
    book_id = i + 1
    author_id = random.randint(1, 100)
    
    print("INSERT INTO Written (BookID, AuthorID) VALUES (%s, %s)" % (book_id, author_id))

Таблица Released:

In [ ]:
import random

for i in range(1000):
    book_id = i + 1
    pub_id = random.randint(1, 50)
    
    print("INSERT INTO Released (BookID, ИздательствоID) VALUES (%s, %s)" % (book_id, pub_id))

Таблица IssuedBy:

In [ ]:
import random

for i in range(1000):
    worker_id = random.randint(1, 50)
    reserve_id = i + 1
    
    print("INSERT INTO IssuedBy (СотрудникID, РезервID) VALUES (%s, %s)" % (worker_id, reserve_id))

Таблица PickUP:

In [ ]:
import random
from faker import Faker

fake = Faker()

for i in range(1000):
    reader_id = random.randint(1, 1000)
    rent_id = random.randint(1, 1000)
    print(f"INSERT INTO PickUP (НомерЧитБилета, АрендаID) VALUES ({reader_id}, {rent_id});")